const createProjectCard = (project) => {
  const projectCard = document.createElement("div");
  projectCard.classList.add("project-card");

  const imgWrap = document.createElement("div");
  imgWrap.classList.add("project-img-wrap");
  const projectImg = document.createElement("img");
  imgWrap.append(projectImg);
  projectImg.src = project.imgUrl;
  projectImg.alt = `A screenshot of Melrin's project ${project.name}`;
  projectImg.classList.add("project-img");

  const projectContent = document.createElement("div");

  const projectTitle = document.createElement("h3");
  projectTitle.textContent = project.name;

  const projectDesc = document.createElement("p");
  projectDesc.textContent = project.desc;

  const projectTech = document.createElement("div");
  project.tech.map((t) => {
    const label = document.createElement("span");
    label.textContent = t;
    projectTech.appendChild(label);
  });
  const projectLinks = document.createElement("div");

  // generated by GPT5
  const regexGithub =
    /^https?:\/\/(www\.)?github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/?$/;

  project.links.map((l) => {
    if (regexGithub.test(l)) {
      const a = document.createElement("a");
      a.textContent = "Source Code";
      a.href = l;
      projectLinks.appendChild(a);
    } else {
      const a = document.createElement("a");
      a.textContent = "Live Demo";
      a.href = l;
      projectLinks.appendChild(a);
    }
  });

  projectContent.append(projectTitle, projectDesc, projectTech, projectLinks);
  projectCard.append(imgWrap, projectContent);

  return projectCard;
};

const populateProjectSection = (projectCards) => {
  const projectSection = document.querySelector(".project-grid");
  projectSection.append(...projectCards);
};
export { createProjectCard, populateProjectSection };
